// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DuplicateCheck.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Duplicate Check Scenatio Outline")]
    public partial class DuplicateCheckScenatioOutlineFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DuplicateCheckScenarioIutline.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Duplicate Check Scenatio Outline", "In order to avoid duplcate entries in the system\r\nAs a user\r\nI want to be told th" +
                    "at I entered a duplicate if a simular person allready exists in the system", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Duplicate check")]
        [NUnit.Framework.TestCaseAttribute("Hans", "Meier", "27.5.1953", "Duplicate", null)]
        [NUnit.Framework.TestCaseAttribute("Hans", "Meier", "27.5.1954", "No duplicate", null)]
        [NUnit.Framework.TestCaseAttribute("Fritz", "Fischer", "27.5.1953", "No duplicate", null)]
        public virtual void DuplicateCheck(string firstName, string lastName, string dateOfBirth, string duplicateCheckResult, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate check", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "LastName",
                        "DateOfBirth"});
            table1.AddRow(new string[] {
                        "Hans",
                        "Meier",
                        "27.5.1953"});
#line 7
 testRunner.Given("I have the following persons in the system:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property",
                        "Value"});
            table2.AddRow(new string[] {
                        "FirstName",
                        string.Format("{0}", firstName)});
            table2.AddRow(new string[] {
                        "LastName",
                        string.Format("{0}", lastName)});
            table2.AddRow(new string[] {
                        "DateOfBirth",
                        string.Format("{0}", dateOfBirth)});
#line 10
 testRunner.When("I add the following person to the system:", ((string)(null)), table2, "When ");
#line 15
 testRunner.Then(string.Format("the duplicate check result is {0}", duplicateCheckResult), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
